name: Add Numbers

on: [push]

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run print command
      run: echo "Hello World""
        
