name: Add Numbers

on: [push]

jobs:
  print command:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run print command
      run: print "Hello World!"
        
