name: hello
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello, World!" 
  deploy:
    name: Job 2
    needs: my-job
    uses: ./ .github/workflows/anusha.sh

   

    

