name: hello
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello, World!" 

  job1:
    runs-on: ubuntu-latest
    steps:
      - name: main step
        run: hi
          
 

   

    

