name: hello
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello, World!" 

  deploy:
    needs: build
    uses: ./ .github/workflows.anusha.sh
          
 

   

    

